### ISSUE TITLE
Rules: brightness, variable as colour value

### ISSUE THREAD

**Issue by joeyboey** [philip1986/pimatic-led-light#69]
It would be nice if you could set the brightness via the rules aswell as being able to input a variable as a colour value, e.g. "set milight to $temp_colour"

**Comment by mwittig** [comment]
Hi, you can change brightness using the dim action which takes a percentage value (0 - 100)! For example:

```
dim led-2 to 25
```

There may be cases where the action does not work as expected. For example, if the the bulb had been offline it may happen the dim action has no effect as driver does not properly retry requests on failure. This is due to shortcomings of the underlying driver package. I am planning to replace thedriver with a more robust implementation in the future.

**Comment by joeyboey** [comment]
Thanks for the quick answer. :) And whats with the variable?

**Comment by mwittig** [comment]
Say you have a variable $brightness you use the action as follows:
```
dim led-2 to $brightness

**Comment by joeyboey** [comment]
i wanted to temporarily store a colour value, then apply it later. 
i think i have to specify the variable type as "hex color" for it to work

Right now i'm getting a " could not find an provider that provides the next action..." error

**Comment by mwittig** [comment]
That's really another issue, isn't it? 

You can specifiy the color by giving one of 140 selected color names or by providing the hexvalue preceded by a hash sign. Providing a variable is not supported at this point!

Examples:
```
set led-2 to red
set led-2 to #FF0000
```

For a list of supported color names see https://github.com/philip1986/pimatic-led-light/blob/master/color_schema.json

**Comment by joeyboey** [comment]
Yes it is. I just signed up for this, I'm not that experienced yet. Thanks
for your quick help :)

Marcus Wittig <notifications@github.com> schrieb am Mi., 25. Jan. 2017,
15:45:

**Comment by mwittig** [comment]
No worries. For general Q&A please also have a look at the pimatic forum. It provides a good source of information and lively exchange between users. https://forum.pimatic.org/
